### ISSUE TITLE
Pairing does not succeed

### ISSUE THREAD

**Issue by jnsaff** [Sonic-Amiga/org.openhab.binding.devireg#1]
Hi,

Thank you for this project and work you have put into it.

I have a DeviSmart thermostat and am trying to control it with OpenHab but am running into problems when trying to pair.

When I enter the App generated code into the /danfoss/ page on openhab the App immediately complains that it could not send the configuration. Then some time later the OpenHab page shows an error as well.

In the logs I see:

```
2021-01-22 09:06:28.649 [TRACE] [ss.discovery.DanfossDiscoveryService] - Pairing with OTP: 1802331
2021-01-22 09:06:28.827 [INFO ] [nfoss.internal.DanfossGridConnection] - Successfully connected to Danfoss grid
2021-01-22 09:06:29.186 [DEBUG] [ss.discovery.DanfossDiscoveryService] - Pairing successful
2021-01-22 09:07:12.733 [WARN ] [nfoss.internal.DanfossGridConnection] - Last user is gone, disconnecting from Danfoss grid
```

Anything I can try to make it work?

**Comment by Sonic-Amiga** [comment]
Hello! Are you using Apple's phone? If so, this is a known problem and frankly speaking i don't know how to fix it. I don't have an iPhone myself.
 It's something disliked by the phone, it refuses to send the config.
 Use Android.

**Comment by jnsaff** [comment]
Yes indeed, this was an iOS problem. When paired via an Android everything works perfectly. Thank you!

**Comment by woopstar** [comment]
@Sonic-Amiga is this still an issue? I'm trying to pair using an iPhone and I just get timeouts.

```
Failed to connect to the sender: java.rmi.RemoteException: Connection refused by grid: 1
```
yet the log states:

```
15:24:48.822 [TRACE] [oss.discovery.DanfossDiscoveryService] - Pairing with OTP: 6876462
15:24:48.996 [DEBUG] [oss.discovery.DanfossDiscoveryService] - Pairing successful
```

**Comment by Sonic-Amiga** [comment]
Hi! Yes, it is still an issue. And i have no time to work on it
